customhost = "employee-db.cfi88m26gavh.ap-south-1.rds.amazonaws.com"
customuser = "groupProject"
custompass = "rpm-aws-2024"
customdb = "employee-db"
custombucket = "rom-aws-employee"
customregion = "ap-south-1"
